// tiendaonline_react/client/src/productos/productos.js
import React, { Component } from 'react';
import './productos.css';
import Barrasuperior from '../barrasuperior/barrasuperior';

class Productos extends Component {
  
  constructor(props){
    super(props);

    if(localStorage.getItem('isLoggedIn') === "true"){
    }else{
      window.location.href = '/';
    }

    //localStorage.setItem('carrito', "");

    this.state = {
      productos:[],
      valueBuscar: '',
      carrito: localStorage.getItem('carrito').length > 0 ? JSON.parse(localStorage.getItem('carrito')) : [],
      id:0
    };

    this.handleChange = this.handleChange.bind(this);
  };

  handleChange(event){
      this.setState({valueBuscar: event.target.value});
      this.getProductos(event.target.value);
  }

  componentWillMount(){
    this.getProductos("");
  }

  getProductos(producto){
    this.state.productos = [];
    var data = {articulo: producto};
    fetch('/api/productos', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    })
    .then(response => response.json())
    .then(productos =>{
      productos.forEach(producto => {
        let data = producto;
        this.setState({productos:this.state.productos.concat([data])});
      })
    });
  };

  verDetalle(event){
    window.location.href = '/detalle/' + event.target.name;
  }

  getCarrito(id){
    
    var producto = {
      nombre:document.getElementById('nom'+id).attributes.name.value,
      unidadCompra:document.getElementById('cant'+id).value,
      imagen:document.getElementById('img'+id).attributes.name.value,
      precio:document.getElementById('pre'+id).attributes.name.value,
      idUsuario:0,
      idProducto:id
    };
    
    if (producto.unidadCompra > 0){}else{producto.unidadCompra = 1}

    if (producto.unidadCompra > 0){
      var index = this.state.carrito.findIndex(function(elemento){
        return elemento.nombre == producto.nombre;
      });
      console.log(index)
      if (index >= 0){
        this.state.carrito[index].unidadCompra = +this.state.carrito[index].unidadCompra + +producto.unidadCompra;
      }else{
        producto.idUsuario = localStorage.getItem('isLoggedId');
        this.state.carrito.push(producto);
      }
      
      localStorage.setItem('carrito',JSON.stringify(this.state.carrito));

      document.getElementById("badgeCart").innerHTML = this.state.carrito.length.toString();

      console.log(this.state.carrito);
      console.log(JSON.parse(localStorage.getItem('carrito')));
    }
    
  }

  render()
  {
    return (
      <div>
        <Barrasuperior />
        <br/>
        <br/>
        <br/>
        <div className="container">
          <div className="row">
            <div className="col s12 m6 l8">
                <h4>Catálogo de Productos</h4>
            </div>
            
            <div className="col s12 m6 l4">
              <h5>¿Que estás buscando?</h5>
              <input placeholder="Buscar producto" type="text" className="browser-default input-buscar" value={this.state.valueBuscar} onChange={this.handleChange}/>
            </div>
          </div>
        </div>
      
        <div className="container">
          <div className="row">
          {this.state.productos.map((item, i) => {
            return <div key={i} className="col s12 m6 l3">

              <div id={'nom'+item["id"]} name={item["nombre"]}></div>
              <div id={'pre'+item["id"]} name={item["precio"]}></div>
              <div id={'img'+item["id"]} name={item["imagen"]}></div>
              
              <div className="card">
                <div className="card-image">
                <img src={item["img"]}></img>
                </div>
                <div className="card-content">
                  <h5>{item["nombre"]}</h5>
                  <h6>Precio: {item["precio"]}</h6>
                  <h6>Unidades disponibles: {item["disponible"]}</h6>
                </div>
                <div className="card-action">
                  <a className='btn btn-vermas' name={item["nombre"]} onClick={this.verDetalle.bind()}>Ver mas</a>
                  <a className="waves-effect waves-light btn-small orange btn-anadir" id={item['id']} onClick={event => {this.getCarrito(event.target.id)}} >Añadir</a>
                  <input type="number" className="browser-default input-cant" id={'cant'+item["id"]} />
                </div>
              </div>
            </div>
          })}
          </div>
        </div>
        </div>
    );
  }
}
/*
function getProductos(producto){
  var data = {articulo: producto};
  const resultado = fetch('/api/productos', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(data),
  });

  var productosArray = [];
  Object.keys(resultado).forEach(function(key) {
    productosArray.push(resultado[key]);
  });
  return productosArray;
};
*/
export default Productos;

// tiendaonline_angular/src/app/productos/productos.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpService } from '.././http.service';
import {Router} from "@angular/router";

@Component({
  selector: 'productos',
  templateUrl: './productos.component.html',
  styleUrls: ['./productos.component.css']
})
export class ProductosComponent implements OnInit {
  productos: any[] = [];
  productoDet: any[] = [];
  carrito: any[] = localStorage.getItem('carrito').length > 0 ? JSON.parse(localStorage.getItem('carrito')) : [];
  showDetalle: boolean = false;
  
  constructor(private httpService: HttpService, private router: Router) { }

  ngOnInit() {
    if(localStorage.getItem('isLoggedIn') == "true"){
      this.retrieveProductos('');
    }else{
      this.router.navigate(['']);
    }

    if (this.carrito.length > 0){
      document.getElementById("badgeCart").innerHTML = this.carrito.length.toString();
    }else{
      document.getElementById("badgeCart").innerHTML = '0';
    }
  }

  onSearchChange(searchValue : string) {  
    this.retrieveProductos(searchValue);
  }

  retrieveProductos(searchValue : string){
    this.httpService.getProductos(searchValue)
      .subscribe(respuesta => {
        if(respuesta.msg == 'OK'){
          this.productos = respuesta.productos;
        }
      });
  }
  
  getCarrito(producto:any, unidades:number){
    if (unidades > 0){
      var index = this.carrito.findIndex(function(elemento){
        return elemento.nombre == producto.nombre;
      });
      console.log(index)
      if (index >= 0){
        this.carrito[index].unidadCompra = +this.carrito[index].unidadCompra + +unidades;
      }else{
        producto.unidadCompra = +unidades;
        producto.idUsuario = localStorage.getItem('isLoggedId');
        this.carrito.push(producto);
      }
      
      localStorage.setItem('carrito',JSON.stringify(this.carrito));

      if (this.showDetalle){this.showDetalle = false;}

      document.getElementById("badgeCart").innerHTML = this.carrito.length.toString();

      console.log(this.carrito);
      console.log(JSON.parse(localStorage.getItem('carrito')));
    }
  }
  
  verDetalle(nameProducto:string){
    if (nameProducto.length > 0 && !this.showDetalle){
      this.showDetalle = true;
      this.httpService.getProductos(nameProducto)
      .subscribe(respuesta => {
        if(respuesta.msg == 'OK'){
          this.productoDet = respuesta.productos;
        }
      });
    }else{
      this.showDetalle = false;
    }
  }
}

<div *ngIf="showDetalle; then detallesBlock; else tiendaBlock"></div>

<ng-template #tiendaBlock>
  <div class="container">
    <div class="row" style="width: 100%; margin: 0%; padding: 0%">
      <div class="col s12 m6 l8" style="text-align: left; margin: 0%; padding: 0%">
          <h4>Catálogo de Productos</h4>
      </div>
      
      <div class="col s12 m6 l4" style="text-align: left; margin: 0%; padding: 0%">
        <h5>¿Que estás buscando?</h5>
        <input placeholder="Buscar producto" type="text" class="browser-default" style="width: 80%; border-bottom: 0rem" (input)="onSearchChange($event.target.value)">
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row" style="width: 100%; margin: 0%; padding: 0%">
      <div *ngFor="let producto of productos" class="col s12 m6 l3">
        <div class="card">
          <div class="card-image">
            <img [src]="'src/img/' + producto.imagen" style="height: 10rem">
          </div>
          <div class="card-content">
            <h5>{{producto.nombre}}</h5>
            <h6>Precio: {{producto.precio}}</h6>
            <h6>Unidades disponibles: {{producto.disponible}}</h6>
          </div>
          <div class="card-action" style="width: 100%; margin: 0%; padding: 0%">
            <a class='btn' style="margin: 1%; width: 45%;color: white;text-transform: none" (click)="verDetalle(producto.nombre)">Ver mas</a>
            <a class="waves-effect waves-light btn-small orange" style="margin: 1%; width: 30%;color: white;text-transform: none" (click)="getCarrito(producto, unidadCompra.value)">Añadir</a>
            <input type="number" class="browser-default" value="1" style="width: 15%; height: 2rem; border-bottom: 0rem; padding: 0%; margin: 2%" #unidadCompra/>
          </div>
        </div>
      </div>
    </div>
  </div>
</ng-template>

<ng-template #detallesBlock>
    <div class="container">
        <div class="row" *ngFor="let pto of productoDet">
          <div class="card">
            <div class="col s4">
              <div class="card-image">
                <img [src]="'src/img/' + pto.imagen" style="height: 18rem">
              </div>
            </div>
            <div class="col s8">
              <div class="card-content">
                <h5>{{pto.nombre}}</h5>
                <h6>Precio: {{pto.precio}}</h6>
                <h6>Unidades disponibles: {{pto.disponible}}</h6>
              </div>
              <div class="card-action" style="width: 100%; margin: 0%; padding: 0%">
                <a class='btn' style="margin: 1%; width: 40%;color: white" (click)="verDetalle('')" modal>Volver</a>
                <a class="waves-effect waves-light btn-small orange" style="margin: 1%; width: 30%;color: white" (click)="getCarrito(pto, unidadCompraDet.value)">Añadir</a>
                <input type="number" class="browser-default" value="1" style="width: 20%; height: 2rem; border-bottom: 0rem; padding: 0%; margin: 2%" #unidadCompraDet/>
              </div>
            </div>
          </div>
        </div>
      </div>
</ng-template>
