// tiendaonline_react/client/src/barrasuperior/barrasuperior.js
import React, { Component } from 'react';
import './barrasuperior.css';

class Barrasuperior extends Component {
  state = {
    carrito: localStorage.getItem('carrito').length > 0 ? JSON.parse(localStorage.getItem('carrito')) : []
  }
  constructor(){
    super();

    
  }

  OnSalir(){
      localStorage.setItem('isLoggedIn', "false");
      localStorage.setItem('carrito',"");
      window.location.href = '/';
  }

  render()
  {
    return (
      <div className="navbar-fixed">
        <nav>
          <div className="nav-wrapper">
            <a className="brand-logo" href="/productos"><h5>La Bodega</h5></a>
            <ul className="right hide-on-med-and-down">
              <li><a href="/productos"><i className="material-icons">apps</i></a></li>
              <li><a href="/pedido"><i className="material-icons notif">shopping_cart</i><small id="badgeCart" className="notification-badge">{this.state.carrito.length.toString()}</small></a></li>
              <li><a href="/productos"><i className="material-icons">inbox</i></a></li>
              <li><a onClick={this.OnSalir} href="/"><i className="material-icons">exit_to_app</i></a></li>
            </ul>
          </div>
        </nav>
      </div>
      
    );
  }
}

export default Barrasuperior;

// tiendaonline_angular/src/app/barra-superior/barra-superior.component.ts
import { Component, OnInit } from '@angular/core';

import {Router} from "@angular/router";

@Component({
  selector: 'barra-superior',
  templateUrl: './barra-superior.component.html',
  styleUrls: ['./barra-superior.component.css']
})
export class BarraSuperiorComponent implements OnInit {

  constructor(private router:Router) { }

  ngOnInit() {
  }

  OnSalir(){
    localStorage.setItem('isLoggedIn', "false");
    localStorage.setItem('carrito',"");
  }

  verPedido(){
    this.router.navigate(['pedido']);
  }
}

<!DOCTYPE html>
<html>
   <head>
      <meta name = "viewport" content = "width = device-width, initial-scale = 1">      
      <link rel = "stylesheet"
         href = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
      
   </head>
   <body>
     
<nav>
  <div class="nav-wrapper">
    <a [routerLink]="['principal']" class="brand-logo"><h5>La Bodega</h5></a>
    <ul class="right hide-on-med-and-down">
      <li><a [routerLink]="['principal']"><i class="material-icons">apps</i></a></li>
      <li><a [routerLink]="['pedido']" (click)="verPedido()"><i class="material-icons notif">shopping_cart</i><small id="badgeCart" class="notification-badge">0</small></a></li>
      <li><a [routerLink]="['principal']"><i class="material-icons">inbox</i></a></li>
      <li><a [routerLink]="['']" (click)="OnSalir()"><i class="material-icons">exit_to_app</i></a></li>
    </ul>
  </div>
</nav>

   
   </body>
</html>
