// tiendaonline_angular/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpService } from '.././http.service';

import {Router} from "@angular/router";

@Component({
  selector: 'login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(private httpService: HttpService, private router: Router) { }

  ngOnInit() {
    localStorage.setItem('isLoggedIn', "false");
  }

  enviarForm(form){
    //this.data = this.dataService.login(form.value);
    //this.dataService.login(form.value);
    this.httpService.login(form.value)
      .subscribe(respuesta => {
        if (respuesta['msg'] == 'OK'){
          //alert('Bienvenido');
          localStorage.setItem('isLoggedIn', "true");
          localStorage.setItem('isLoggedId', respuesta['id']);
          this.router.navigate(['principal']);
        }else{
          localStorage.setItem('isLoggedIn', "false");
          alert(respuesta['msg']);
        }
      });
  }
}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Login</title>
  </head>
  <body>
    <div class="main">
      <div class="login-container">
        <h4>Inicia sesión</h4>
        <form (ngSubmit)="enviarForm(f)" #f="ngForm">
          <div class="row align-center">
            <div class="col s12">
              <label for="email-input">Dirección correo electrónico
                <input type="email" id="username" ngModel name="usuario" required pattern="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?">
              </label>
            </div>
          </div>
          <div class="row align-center">
            <div class="col s12">
              <label>Contraseña
                <input type="password" id="password" ngModel name="contrasena" required>
              </label>
            </div>
          </div>
          <div class="row align-center">
            <div class="col s12 error-container">
              <label class="error" *ngIf="!f.valid">El email debe ser valido y la contraseña es obligatoria</label>
            </div>
          </div>
          <div class="row align-center">
            <div class="col s12 btn-container">
              <button class="waves-effect waves-light btn">Ingresar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

// tiendaonline_react/client/src/login/login.js
import React, { Component } from 'react';
import './login.css';

class Login extends Component {
  state = {
    usuario: this.props.usuario,
    contrasena: this.props.contrasena,
    id:this.props.id,
  };

  handleSubmit = async e => {
    e.preventDefault();
    var data = {usuario: this.state.usuario, contrasena: this.state.contrasena};
    const response = await fetch('/api/login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    const body = await response.text();
    
    if (JSON.parse(body).length > 0){
        if (JSON.parse(body)[0].msg === "OK"){
            alert('Bienvenido');
            this.setState({ id: JSON.parse(body)[0].id });
            localStorage.setItem('isLoggedIn', "true");
            localStorage.setItem('isLoggedId', JSON.parse(body)[0].id);
            window.location.href = '/productos';
            //document.form.submit();
        }else{
            localStorage.setItem('isLoggedIn', "false");
            alert(body[0].msg);
        }
    }else{
        alert('Se presento error al comunicarse con el servidor');
    }
  };

  render()
  {
      
    return (
        <div className="Login">
          <div className="main">
              <div className="login-container">
                  <h4>Inicia sesión</h4>
                  <form onSubmit={this.handleSubmit}>
                      <div className="row align-center">
                          <div className="col s12">
                              <label htmlFor="usuario">Dirección correo electrónico
                                  <input type="email" name="usuario" value={this.state.usuario} onChange={e => this.setState({ usuario: e.target.value })} required pattern="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?" />
                              </label>
                          </div>
                      </div>
                      <div className="row align-center">
                          <div className="col s12">
                              <label htmlFor="contrasena">Contraseña
                                  <input type="password" value={this.state.contrasena} onChange={e => this.setState({ contrasena: e.target.value })} name="contrasena" required />
                              </label>
                          </div>
                      </div>
                      <div className="row align-center">
                          <div className="col s12 error-container"></div>
                      </div>
                      <div className="row align-center">
                          <div className="col s12 btn-container">
                              <button className="waves-effect waves-light btn" type="submit" value="Submit">Ingresar</button>
                          </div>
                      </div>
                  </form>
              </div>
          </div>
      </div>

    );
  }
}

export default Login;
