// tiendaonline_angular/src/app/pedido/pedido.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpService } from '.././http.service';
import {Router} from "@angular/router";

@Component({
  selector: 'pedido',
  templateUrl: './pedido.component.html',
  styleUrls: ['./pedido.component.css']
})
export class PedidoComponent implements OnInit {
  carrito: any[] = localStorage.getItem('carrito').length > 0 ? JSON.parse(localStorage.getItem('carrito')) : [];
  totalPedido = 0;
  
  constructor(private httpService: HttpService, private router: Router) { }

  ngOnInit() {
    this.carrito.forEach((value) => {this.totalPedido += (value.unidadCompra * value.precio);});
    //this.totalPedido = this.formatNumber.new(this.totalPedido, "$");
    if (this.carrito.length > 0){
      document.getElementById("badgeCart").innerHTML = this.carrito.length.toString();
    }else{
      document.getElementById("badgeCart").innerHTML = '0';
    }
  }
  
  formatNumber = {
    separador: ".", // separador para los miles
    sepDecimal: ',', // separador para los decimales
    formatear:function (num){
      num +='';
      var splitStr = num.split('.');
      var splitLeft = splitStr[0];
      var splitRight = splitStr.length > 1 ? this.sepDecimal + splitStr[1] : '';
      var regx = /(\d+)(\d{3})/;
      while (regx.test(splitLeft)) {
        splitLeft = splitLeft.replace(regx, '$1' + this.separador + '$2');
      }
      return this.simbol + splitLeft +splitRight;
    },
    new:function(num, simbol){
      this.simbol = simbol ||'';
      return this.formatear(num);
    }
  }

  confirmarPedido(){
    this.httpService.setPedido(this.carrito)
      .subscribe(respuesta => {
        if(respuesta.msg == 'OK'){
          alert("El pedido se grabo satisfactoriamente.");
          localStorage.setItem('carrito',"");
          this.router.navigate(['principal']);
        }else{
          alert(respuesta.msg);
        }
      });
  }
}

<barra-superior class="navbar-fixed"></barra-superior>
<br>
<br>
<br>
<br>
<table class="bordered striped highlight responsive-table">
  <thead>
    <tr>
      <th></th>
      <th style="text-align: center">Descripción</th>
      <th style="text-align: center">Precio</th>
      <th style="text-align: center">Cantidad</th>
      <th style="text-align: center">Total</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let pto of carrito">
      <td style="text-align: center; width: 0%"><img [src]="'src/img/' + pto.imagen" style="height: 4rem;border: 0ch;padding: 0%"></td>
      <td style="text-align: left">{{pto.nombre}}</td>
      <td style="text-align: right">{{formatNumber.new(pto.precio, "$")}}</td>
      <td style="text-align: center">{{formatNumber.new(pto.unidadCompra)}}</td>
      <td style="text-align: right">{{formatNumber.new(pto.unidadCompra * pto.precio, "$")}}</td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>TOTAL:</td>
      <td style="text-align: right">{{formatNumber.new(totalPedido, "$")}}</td>
    </tr>
  </tfoot>
</table>

<div class="card-action" style="width: 100%; margin: 0%; padding: 0%; text-align: right">
  <a class='btn' [href]="'principal'" style="margin: 1%; width: 10%;color: white">Volver</a>
  <a class="waves-effect waves-light btn-small orange" style="margin: 1%; width: 10%;color: white" (click)="confirmarPedido()">Confirmar</a>
</div>

// tiendaonline_react/client/src/pedido/pedido.js
import React, { Component } from 'react';
import './pedido.css';

import Barrasuperior from '../barrasuperior/barrasuperior';

class Pedido extends Component {
    state = {
        carrito:localStorage.getItem('carrito').length > 0 ? JSON.parse(localStorage.getItem('carrito')) : [],
        totalPedido:0
    }

  constructor(){
    super();

    
  }

  componentWillMount(){
    this.state.carrito.forEach((value) => {this.state.totalPedido += (value.unidadCompra * value.precio);});
  }

  confirmarPedido(){
    fetch('/api/setpedido', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(JSON.parse(localStorage.getItem('carrito'))),
      })
      .then(response => response.json())
      .then(respuesta =>{
        if (respuesta[0].msg === "OK"){
            localStorage.setItem('carrito', '');
            alert('Pedido creado');
            window.location.href = '/productos';
        }else{
            alert(respuesta.msg);
        }
      });
}

  render()
  {
    return (
        <div>
            <Barrasuperior />
            <br/>
            <br/>
            <br/>
            <br/>
            <table className="bordered striped highlight responsive-table" style={{backgroundColor: 'white'}}>
                <thead>
                    <tr>
                        <th></th>
                        <th style={{textalign: 'center'}}>Descripción</th>
                        <th style={{textalign: 'center'}}>Precio</th>
                        <th style={{textalign: 'center'}}>Cantidad</th>
                        <th style={{textalign: 'center'}}>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {this.state.carrito.map((item, i) => {
                        return <tr key={i}>
                            <td style={{textalign: 'center', width: '0%'}}><img src={'../img/'+item["imagen"]} style={{height: '4rem',border: '0ch',padding: '0%'}} /></td>
                            <td style={{textalign: 'left'}}>{item["nombre"]}</td>
                            <td style={{textalign: 'right'}}>{item["precio"]}</td>
                            <td style={{textalign: 'center'}}>{item["unidadCompra"]}</td>
                            <td style={{textalign: 'right'}}>{item["unidadCompra"] * item["precio"]}</td>
                        </tr>
                    })}
                </tbody>
                <tfoot>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>TOTAL:</td>
                        <td style={{textalign: 'right'}}>{this.state.totalPedido}</td>
                    </tr>
                </tfoot>
            </table>
            
            <div className="card-action" style={{width: '100%', margin: '0%', padding: '0%', textalign: 'right'}}>
                <a className='btn' href="/productos" style={{margin: '1%', width: '10%',color: 'white'}}>Volver</a>
                <a className="waves-effect waves-light btn-small orange" style={{margin: '1%', width: '10%',color: 'white'}} onClick={this.confirmarPedido.bind()}>Confirmar</a>
            </div>
        </div>
      
    );
  }
}

export default Pedido;
